# -*- coding: utf-8 -*-
"""
ComfyUI 批量图生图工具 - 帮助文档
"""

# 帮助文档内容配置
HELP_CONTENT = {
    "chinese": """ComfyUI 生图模式参数配置技术指导文档

一、文档说明
本文档用于指导用户通过配置 *.ini 文件结合 (*)_API.json 文件（ComfyUI 工作流 "文件→导出 (API)" 生成），实现图生图、文生图两类核心生图模式的参数匹配与调整。程序暂不支持在内部微调大模型，但可通过 *.ini + (*)_API.json 组合命名的方式，为不同大模型单独配置 (*)_API.json 文件，实现多模型调用（后续版本将优化该交互方式）。

二、核心生图模式及匹配索引
1. 图生图模式
匹配索引名：[图片载入]、[图片尺寸高度]、[图片尺寸宽度]、[K 采样步值]、[图片输出]
2. 文生图（正向提示词）模式
匹配索引名：[正向提示词]、[负面提示词]、[K 采样步值]、[图片尺寸高度]、[图片尺寸宽度]、[图片输出]
3. 文生图（正向 + 负面提示词）模式
匹配索引名：[正向提示词]、[K 采样步值]、[图片尺寸高度]、[图片尺寸宽度]、[图片输出]

三、配置文件格式规范（以图生图模式为例）
通用配置项说明
每个索引名对应独立的配置块，包含以下固定字段：

配置字段      | 说明
-------------|--------------------------------------------------------
变量序号      | 该参数在模式中的排序编号（自增，从 1 开始）
变量名称      | ComfyUI 工作流中节点的名称（格式：节点 ID - 节点展示名称）
参数键名      | 节点输入参数的键名（如 image/height/width/steps 等）
参数值        | 该参数的具体取值（根据实际需求调整）
数据节点路径  | 对应 (*)_API.json 中参数的 JSON 路径（格式：data ["节点 ID"]["inputs"]["参数键名"]）
变量代码      | 对应 (*)_API.json 中该节点的完整 JSON 片段（需保持语法正确）
变量绑定      | 绑定的核心索引名（与模式匹配的索引名一致）


图生图模式配置示例(ini):
[图片载入]
变量序号 = 1
变量名称 = 44-加载图像
参数键名 = image
参数值 = 1 (1).png
数据节点路径 = data["44"]["inputs"]["image"]
变量代码 = "44": {"inputs":{"image":"1 (1).png"},"class_type":"LoadImage","_meta":{"title":"加载图像"}}
变量绑定 = 图片载入

[图片尺寸高度]
变量序号 = 2
变量名称 = 49-🔧 Image Resize
参数键名 = height
参数值 = 1536
数据节点路径 = data["49"]["inputs"]["height"]
变量代码 = "49": {"inputs":{"width":1024,"height":1536,"interpolation":"nearest","method":"keep proportion","condition":"always","multiple_of":0,"image":["44",0]},"class_type":"ImageResize+","_meta":{"title":"🔧 Image Resize"}}
变量绑定 = 图片尺寸高度

[图片尺寸宽度]
变量序号 = 3
变量名称 = 49-🔧 Image Resize
参数键名 = width
参数值 = 1024
数据节点路径 = data["49"]["inputs"]["width"]
变量代码 = "49": {"inputs":{"width":1024,"height":1536,"interpolation":"nearest","method":"keep proportion","condition":"always","multiple_of":0,"image":["44",0]},"class_type":"ImageResize+","_meta":{"title":"🔧 Image Resize"}}
变量绑定 = 图片尺寸宽度

[K采样步值]
变量序号 = 4
变量名称 = 17-基本调度器
参数键名 = steps
参数值 = 20
数据节点路径 = data["17"]["inputs"]["steps"]
变量代码 = "17": {"inputs":{"scheduler":"simple","steps":20,"denoise":["72",0],"model":["79",0]},"class_type":"BasicScheduler","_meta":{"title":"基本调度器"}}
变量绑定 = K采样步值

[图片输出]
变量序号 = 5
变量名称 = 9-保存图像
参数键名 = filename_prefix
参数值 = ComfyUI
数据节点路径 = data["9"]["inputs"]["filename_prefix"]
变量代码 = "9": {"inputs":{"filename_prefix":"ComfyUI","images":["63",0]},"class_type":"SaveImage","_meta":{"title":"保存图像"}}
变量绑定 = 图片输出

四、配置要点
(*)_API.json 文件必须通过 ComfyUI 工作流的 "文件→导出 (API)" 功能生成，不可直接使用普通 JSON 工作流文件。
*.ini 文件中每个配置块的「变量代码」需与 (*)_API.json 中对应节点的 JSON 结构完全一致，仅调整「参数值」部分。
多大模型适配：在 ComfyUI 工作流中调整大模型类别后，导出新的 (*)_API.json 文件并单独命名，配合同名前缀的 *.ini 文件，即可实现不同大模型的参数配置与调用。
参数调整原则：仅修改「参数值」字段，其余字段（如数据节点路径、变量代码结构）需与 (*)_API.json 中的节点定义保持一致，避免配置失效。

五、反馈与优化
若对现有配置方式有优化建议（如更人性化的多模型管理、参数调整方式），欢迎向作者反馈，后续版本将结合用户需求迭代优化。""",
    
    "english": """ComfyUI Image Generation Mode Parameter Configuration Technical Guide

1. Document Description
This document guides users to implement parameter matching and adjustment for two core image generation modes (image-to-image and text-to-image) by configuring *.ini files combined with (*)_API.json files (generated by ComfyUI workflow "File → Export (API)"). The program currently does not support fine-tuning large models internally, but can separately configure (*)_API.json files for different large models through the combination naming method of *.ini + (*)_API.json to achieve multi-model calling (this interaction method will be optimized in subsequent versions).

2. Core Image Generation Modes and Matching Indexes
1. Image-to-Image Mode
Matching index names: [Image Loading], [Image Height], [Image Width], [K Sampling Steps], [Image Output]
2. Text-to-Image (Positive Prompt Only) Mode
Matching index names: [Positive Prompt], [Negative Prompt], [K Sampling Steps], [Image Height], [Image Width], [Image Output]
3. Text-to-Image (Positive + Negative Prompt) Mode
Matching index names: [Positive Prompt], [K Sampling Steps], [Image Height], [Image Width], [Image Output]

3. Configuration File Format Specification (Taking Image-to-Image Mode as Example)
General Configuration Item Description
Each index name corresponds to an independent configuration block, containing the following fixed fields:

Configuration Field      | Description
-------------------------|--------------------------------------------------------
Variable Number          | The serial number of the parameter in the mode (auto-increment, starting from 1)
Variable Name            | The name of the node in the ComfyUI workflow (format: Node ID - Node Display Name)
Parameter Key Name       | The key name of the node input parameter (such as image/height/width/steps, etc.)
Parameter Value          | The specific value of the parameter (adjust according to actual needs)
Data Node Path           | The JSON path of the parameter in (*)_API.json (format: data ["Node ID"]["inputs"]["Parameter Key Name"])
Variable Code            | The complete JSON fragment of the node in (*)_API.json (must maintain correct syntax)
Variable Binding         | The bound core index name (consistent with the index name matching the mode)

Image-to-Image Mode Configuration Example(ini)
[Image Loading]
Variable Number = 1
Variable Name = 44-Load Image
Parameter Key Name = image
Parameter Value = 1 (1).png
Data Node Path = data["44"]["inputs"]["image"]
Variable Code = "44": {"inputs":{"image":"1 (1).png"},"class_type":"LoadImage","_meta":{"title":"Load Image"}}
Variable Binding = Image Loading

[Image Height]
Variable Number = 2
Variable Name = 49-🔧 Image Resize
Parameter Key Name = height
Parameter Value = 1536
Data Node Path = data["49"]["inputs"]["height"]
Variable Code = "49": {"inputs":{"width":1024,"height":1536,"interpolation":"nearest","method":"keep proportion","condition":"always","multiple_of":0,"image":["44",0]},"class_type":"ImageResize+","_meta":{"title":"🔧 Image Resize"}}
Variable Binding = Image Height

[Image Width]
Variable Number = 3
Variable Name = 49-🔧 Image Resize
Parameter Key Name = width
Parameter Value = 1024
Data Node Path = data["49"]["inputs"]["width"]
Variable Code = "49": {"inputs":{"width":1024,"height":1536,"interpolation":"nearest","method":"keep proportion","condition":"always","multiple_of":0,"image":["44",0]},"class_type":"ImageResize+","_meta":{"title":"🔧 Image Resize"}}
Variable Binding = Image Width

[K Sampling Steps]
Variable Number = 4
Variable Name = 17-Basic Scheduler
Parameter Key Name = steps
Parameter Value = 20
Data Node Path = data["17"]["inputs"]["steps"]
Variable Code = "17": {"inputs":{"scheduler":"simple","steps":20,"denoise":["72",0],"model":["79",0]},"class_type":"BasicScheduler","_meta":{"title":"Basic Scheduler"}}
Variable Binding = K Sampling Steps

[Image Output]
Variable Number = 5
Variable Name = 9-Save Image
Parameter Key Name = filename_prefix
Parameter Value = ComfyUI
Data Node Path = data["9"]["inputs"]["filename_prefix"]
Variable Code = "9": {"inputs":{"filename_prefix":"ComfyUI","images":["63",0]},"class_type":"SaveImage","_meta":{"title":"Save Image"}}
Variable Binding = Image Output

4. Configuration Points
The (*)_API.json file must be generated through the "File → Export (API)" function of the ComfyUI workflow, and cannot directly use ordinary JSON workflow files.
The "Variable Code" of each configuration block in the *.ini file must be completely consistent with the JSON structure of the corresponding node in (*)_API.json, only adjusting the "Parameter Value" part.
Multi-model adaptation: After adjusting the large model category in the ComfyUI workflow, export a new (*)_API.json file and name it separately, and match it with the *.ini file with the same name prefix to achieve parameter configuration and calling of different large models.
Parameter adjustment principle: Only modify the "Parameter Value" field, and other fields (such as data node path, variable code structure) must be consistent with the node definition in (*)_API.json to avoid configuration failure.

5. Feedback and Optimization
If you have optimization suggestions for the existing configuration method (such as more user-friendly multi-model management, parameter adjustment methods), please provide feedback to the author. Subsequent versions will be iteratively optimized based on user needs."""
}


def get_help_content(language="chinese"):
    """
    获取帮助文档内容
    
    Args:
        language (str): 语言，可选值："chinese" 或 "english"
        
    Returns:
        str: 对应语言的帮助文档内容
    """
    return HELP_CONTENT.get(language, HELP_CONTENT["chinese"])
